FROM rust-builder as builder
FROM debian:bookworm-slim
ARG HOG="choctaw"
ENV HOG_BIN="${HOG}_hog"
COPY --from=builder /build/target/release/$HOG_BIN /usr/local/bin/
ENTRYPOINT /usr/local/bin/$HOG_BIN
